Added styles for buttons in UI Kit module
CashAdv/CashADV pull request #39
Opened 2023-12-04 14:24 UTC by RinatGiniyatullin

Feature/16-button-styles

2023-12-05 08:35 UTC, avanisimov commented on uikit/src/main/res/values/styles.xml
> +      <style name="BlackButton10" parent="Widget.MaterialComponents.Button.UnelevatedButton">
1 - стили для кнопок и стили для текстов лучше разделить по разным файлам, чтобы огромной портянки не было
2 - для именования стилей кнопок лучше использовать префикс "Widget.CashAdvisor.Button"  и потом делать иерархию стилей через наследование по точке (можно посмотреть как в текстах сделано)
3 - для бекграунда кнопок и цвета текста нужно делать селекторы состояний (enabled, disabled, pressed и тд)
4 - надо проверить нужны ли кастомные шрифты в кнопках

2023-12-05 12:25 UTC, artwist-polyakov requested changes
В целом поддерживаю то, что предложил Алексей, плюс добавил, что нет смысла создавать кучу дровабл для картинок, а просто достаточно обойтись селекторами под разные состояния

2023-12-05 12:25 UTC, artwist-polyakov commented on uikit/src/main/res/drawable/button_bg1_15.xml
@RinatGiniyatullin привет

вижу, что ты делаешь одообразные кнопки покрашенные в разные цвета, но я бы рекомендовал посмотреть в сторону селекторов, которые будут управлять цветами элемента при изменении его состояния

https://habr.com/ru/articles/206012/

вот тут можно посмотреть пример, ну или погуглить что-то про selectors for button background xml

2023-12-11 15:23 UTC, artwist-polyakov approved these changes
отлично, что используешь селекторы

2023-12-13 16:58 UTC, avanisimov approved these changes

2023-12-13 16:58 UTC, merged