Feature/37 timber setup
CashAdv/CashADV pull request #42
Opened 2023-12-09 09:15 UTC by artwist-polyakov

2023-12-09 09:19 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/main/presentation/ui/MainActivity.kt
> +//                throw RuntimeException("This is a test crash.")
я бы для демонстрации работы сделал прям краш

2023-12-09 09:25 UTC, artwist-polyakov commented on app/src/main/java/app/cashadvisor/main/presentation/ui/MainActivity.kt
> +//                throw RuntimeException("This is a test crash.")
Так а он есть) просто закомменченный, так как я бился с ворнингами и падать приложению не требовалось

2023-12-09 19:14 UTC, artwist-polyakov commented on app/src/main/java/app/cashadvisor/main/presentation/ui/MainActivity.kt
> +//                throw RuntimeException("This is a test crash.")
@avanisimov раскомментировал

2023-12-10 11:05 UTC, avanisimov approved these changes

2023-12-10 16:18 UTC, JudjinGM requested changes
ревью

2023-12-10 16:23 UTC, JudjinGM approved these changes

2023-12-10 16:31 UTC, merged