feature: Created custom view - Circular diagram 5.
CashAdv/CashADV pull request #45
Opened 2023-12-13 12:26 UTC by Usynin1994

@avanisimov 
Additionally included a library for push notifications.

2023-12-13 17:18 UTC, avanisimov reviewed
надо уточнить как рассчивается пложение текстов внутри вьюхи
у меня они начали налазить друг на друга
![image](https://github.com/CashAdv/CashADV/assets/26187894/7910e01e-206b-4117-9109-6f226772a637)

2023-12-13 17:18 UTC, avanisimov commented on app/build.gradle.kts
> +    implementation(libs.firebase.messaging)
а зачем?

2023-12-13 17:18 UTC, avanisimov commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        }
нужен флаг antiAlias для сглаживания

2023-12-13 17:18 UTC, avanisimov commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText("месяцы", xPos, height.toFloat()-(height.toFloat()/3), paintWord)
текст в ресурсы
никаких текстов в коде

2023-12-13 17:18 UTC, avanisimov commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText("месяцы", xPos, height.toFloat()-(height.toFloat()/3), paintWord)
// Пока захардкодил. Как будут ресурсы - сделать нормально.
так можно самому их создать

2023-12-13 17:19 UTC, avanisimov commented on uikit/src/main/res/values/circle_months_custom_attrs.xml
> +        <attr name="strokeWidthSecond" format="dimension"/>
для аттрибутов кастомных вьюх есть "договорённость" испоьлзовать префикс в виде сокрашения имени вьюхи cdf_
cdf_firstCircleColor
cdf_secondTextSize

2023-12-14 11:33 UTC, Usynin1994 commented on app/build.gradle.kts
> +    implementation(libs.firebase.messaging)
У меня висит issue на подключение пушей, они без этой библиотеки не работают исходя из документации. Но пока пуши сказали не трогать, а в градле она осталась. Но в целом ей в этом ПР делать нечего, уберу.

2023-12-14 11:35 UTC, Usynin1994 commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        }
Сделал

2023-12-14 11:36 UTC, Usynin1994 commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText("месяцы", xPos, height.toFloat()-(height.toFloat()/3), paintWord)
Создал, слово положил

2023-12-14 11:36 UTC, Usynin1994 commented on uikit/src/main/res/values/circle_months_custom_attrs.xml
> +        <attr name="strokeWidthSecond" format="dimension"/>
Поправил

2023-12-14 12:11 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        paintMoths.apply {
Опечатка. Мб имеет смысл дать более абстрактное имя

2023-12-14 12:11 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText(context.getString(R.string.months), xPos, yPosText+(yPosText/6), paintWord)
магическая цифра 6, не понятно, что означает и почему именно 6

2023-12-14 12:11 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +    private var firstTextSize = 120f
лучше все такие значения вынести в константы

2023-12-14 12:11 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +            val typedArray = context.obtainStyledAttributes(attributeSet, R.styleable.CircularDiagramFive)
Как можно выставить шрифт и стиль для текста?

2023-12-14 12:12 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText(context.getString(R.string.months), xPos, yPosText+(yPosText/6), paintWord)
мб имеет смысл вынести текст в атрибуты , чтобы можно было его задавать  снаружи

2023-12-17 11:00 UTC, avanisimov approved these changes

2023-12-18 15:46 UTC, Usynin1994 commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        paintMoths.apply {
Поправил, в целом диаграмма универсальная, можно хоть дни, хоть годы вставлять.

2023-12-18 16:32 UTC, Usynin1994 commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText(context.getString(R.string.months), xPos, yPosText+(yPosText/6), paintWord)
Вынес

2023-12-18 16:40 UTC, Usynin1994 commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +    private var firstTextSize = 120f
Окей

2023-12-18 16:45 UTC, Usynin1994 commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText(context.getString(R.string.months), xPos, yPosText+(yPosText/6), paintWord)
Эта вся конструкция нужна для того, чтобы слово "месяцы" всегда оставалось под текстом с отсчетом независимо от его размеров. Выставлять эту цифру динамически нет возможности, как обозвать это в константе не прибегая к трехэтажной конструкции также не понятно. Предлагаю оставить так.

2023-12-18 17:07 UTC, Usynin1994 commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +            val typedArray = context.obtainStyledAttributes(attributeSet, R.styleable.CircularDiagramFive)
Исправил

2023-12-18 17:20 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText(context.getString(R.string.months), xPos, yPosText+(yPosText/6), paintWord)
а почему радиус вычисляется как четверть высоты вью?

2023-12-18 21:17 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +        canvas.drawText(context.getString(R.string.months), xPos, yPosText+(yPosText/6), paintWord)
https://gist.github.com/JudjinGM/3c6627e14be83dc44c718fb22373d668
Посмотри, пожалуйста, мб вот так переделать, как вариант. Я там долго мучался с вычислением размеров, так как ascent и descent оказались заданными значениями тем кто создавал шрифты, а не реальными размерами текста. В итоге нашел, что размеры можно вычислить через границы. Также предлагаю поменять вычисление радиуса - взять его равным половине минимальной стороне экрана минус половина толщины диаграммы . В твоем случае вью не оборачивает диаграмму и есть некорректные пустые пространства.

2023-12-20 07:38 UTC, JudjinGM requested changes

2023-12-20 07:38 UTC, JudjinGM commented on uikit/src/main/java/customcircle/CircularDiagramFive.kt
> +            yPos + heightWordOne / 2 + heightWordTwo / 2 + dpToPx(textSpacing.toInt())
Я залогировал textSpacing и dpToPx(textSpacing.toInt()) и при установке
5dp в xml вот что приходит в логер: 
textSpacing = 13.125 
dpToPx(textSpacing.toInt()) =  34.125
выглядит так, что из атрибутов ты уже забираешь преобразованное значение(в пикселях). Наверное, надо сделать условие, что если у тебя значение из атрибутов то значение как есть, а если то что ты задаешь сам как дефолтное, то надо делать преобразование. Также, если подтянешь ветку dev, то там будет функция расширение для преобразование (View.dp(dimensionDp: Int): Float), что мне посовтовал сделать Алексей и приватную функцию fun dpToPx() можно удалить и использовать dp(значение для преобразования)

2023-12-21 11:23 UTC, JudjinGM approved these changes

2023-12-23 13:03 UTC, merged