Feature/53 fragment viewmodel registration login
CashAdv/CashADV pull request #86
Opened 2024-04-02 02:03 UTC by Barsec13

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/res/layout/fragment_signup.xml
> +        android:layout_marginTop="@dimen/signup_screen_title_top_margin"
по макетам отступ не 50dp, а 11

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/res/layout/fragment_signup.xml
> +    <app.cashadvisor.customView.authorization.CustomViewSteps
нужен отступ между "Регистрация" и вьюхой шагов 
сейчас они слишком прилепились
![image](https://github.com/CashAdv/CashADV/assets/26187894/36cf3429-dc57-4603-b2a2-39c78dca5616)

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/res/layout/fragment_signup.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
ConstraintLayout тут оверхед, можно всё расположить в LinearLayout

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/res/layout/fragment_signup.xml
> +        app:layout_constraintTop_toTopOf="parent"
констрейнты не нужны

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/res/layout/fragment_signup.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
и завернуть его в скроллвью, чтобы на маленьких устройствах не было проблем 
![image](https://github.com/CashAdv/CashADV/assets/26187894/041d5c71-ff06-474a-a6e1-4614879390f1)

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/res/layout/fragment_signup.xml
> +<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
надо в целом отступы между элементами сверить с макетами

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/ui/SignupFragment.kt
> +            null
можно достать картинку через 
        ContextCompat.getDrawable(requireContext(), app.cashadvisor.uikit.R.drawable.text_input_background_succes)
        
       тогда он возьмет тему из активити и правильно найдет аттрибуты (если они будут в vector-drawable иконке)

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +                EmailValidationState.Default -> TODO()
интерактор никогда не возвращает Default. Лучше его тогда удалить из доменной модели

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +                            delay(VALIDATE_DATA_DELAY_MILLIS)
заддержку кажется лучше делать перед вызовом интерактора

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +    }
это надо делать через plurals https://developer.android.com/guide/topics/resources/string-resource#Plurals

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +        private const val DURATION_CONVERTING_CONST = 60000000000
60000000000 это что?

2024-04-08 11:27 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/models/SignupScreenState.kt
> +sealed interface SignupScreenState {
сейчас сложно понять чем отличается SignupUiState и SignupScreenState по смыслу
 я бы предложил назвать это SignUpStep

2024-04-10 15:27 UTC, Barsec13 commented on app/src/main/res/layout/fragment_signup.xml
> +        android:layout_marginTop="@dimen/signup_screen_title_top_margin"
Исправлено

2024-04-10 15:27 UTC, Barsec13 commented on app/src/main/res/layout/fragment_signup.xml
> +    <app.cashadvisor.customView.authorization.CustomViewSteps
Исправлено

2024-04-10 16:22 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +                            delay(VALIDATE_DATA_DELAY_MILLIS)
Поправил

2024-04-10 16:22 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/ui/SignupFragment.kt
> +            null
Поправил

2024-04-10 16:22 UTC, Barsec13 commented on app/src/main/res/layout/fragment_signup.xml
> +<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
Поправил

2024-04-10 16:22 UTC, Barsec13 commented on app/src/main/res/layout/fragment_signup.xml
> +        app:layout_constraintTop_toTopOf="parent"
Поправил

2024-04-10 16:22 UTC, Barsec13 commented on app/src/main/res/layout/fragment_signup.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Поправил

2024-04-10 16:22 UTC, Barsec13 commented on app/src/main/res/layout/fragment_signup.xml
> +    <app.cashadvisor.customView.authorization.CustomViewSteps
Поправил

2024-04-10 16:22 UTC, Barsec13 commented on app/src/main/res/layout/fragment_signup.xml
> +        android:layout_marginTop="@dimen/signup_screen_title_top_margin"
Поправил

2024-04-10 16:24 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/models/SignupScreenState.kt
> +sealed interface SignupScreenState {
Поправил

2024-04-11 02:00 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +        private const val DURATION_CONVERTING_CONST = 60000000000
Это константа для перевода времени, которое приходит с сервера в наносекундах при исчерпании попыток ввода кода с почты, в минуты

2024-04-11 16:24 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +    }
Поправил_

2024-04-13 14:53 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +                EmailValidationState.Default -> TODO()
Поправил

2024-04-21 16:24 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +        private const val DURATION_CONVERTING_CONST = 60000000000
стоит использовать package kotlin.time
тогда мы называем поле в ДТО как число в наносекундах
   ` @SerialName("lock_duration") val lockDurationNanoseconds: Long,`
а потом переводим это в что хотим и у себя в приложении пользуемся удобной размерностью
`lockDuration = errorResponse.lockDurationNanoseconds.nanoseconds.inWholeMinutes,`

2024-04-21 16:24 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +    }
названия в снейк_кейз нотации
    <plurals name="endingMinutes">

2024-04-22 15:33 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +    }
Поправил

2024-04-22 16:45 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +        private const val DURATION_CONVERTING_CONST = 60000000000
Поправил

2024-04-23 18:42 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +                            delay(VALIDATE_DATA_DELAY_MILLIS)
дак в validateEmail тоже)

2024-04-24 14:31 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/signup/presentation/viewmodel/SignupViewModel.kt
> +        private const val DURATION_CONVERTING_CONST = 60000000000
Больше не нашел где еще нужно поправить

2024-04-27 15:40 UTC, avanisimov approved these changes

2024-04-27 19:18 UTC, artwist-polyakov approved these changes

2024-04-27 19:18 UTC, artwist-polyakov commented on app/src/main/java/app/cashadvisor/authorization/domain/impl/InputValidationInteractorImpl.kt
>              password = Password(EMPTY_VALUE),
Не могу уловить логику почему у тебя для ошибки пароль пустой передаётся?

2024-04-27 19:25 UTC, artwist-polyakov commented
Кстати почему ты выводишь снекбаром ошибки валидации, но выводишь тостом ошибку существования такого аккаунта?  Мне кажется логично использовать одинаковый UI для обоих типов ошибок
![CleanShot 2024-04-27 at 22 24 22@2x](https://github.com/CashAdv/CashADV/assets/42345388/45e940d6-a6bd-4fb8-9cc3-ada7f692cf21)

2024-04-27 19:32 UTC, artwist-polyakov commented
Обрати внимание, что если дойти до подтверждения email, то кнопка назад выбрасывает на главный экран + поймал глюк с валидацией паролей оба глюка на записи https://share.cleanshot.com/ksw07Br9zhqryY62HWB2

2024-04-27 19:33 UTC, artwist-polyakov requested changes
Посмотри, отметил пару глюков на экране регистрации.

2024-05-02 15:28 UTC, Barsec13 commented on app/src/main/java/app/cashadvisor/authorization/domain/impl/InputValidationInteractorImpl.kt
>              password = Password(EMPTY_VALUE),
Посмотрел и правда нигде не используется пароль из ошибки. Убрал для регистрации и для авторизации этот параметр

2024-05-06 15:48 UTC, artwist-polyakov approved these changes
Вроде всё ок, единственное смущает работа проверки корректности почты. Как будто бы не учитывает то, что я продолжаю вводить текст

2024-05-10 05:59 UTC, merged