Feature/76 edit user profile
CashAdv/CashADV pull request #87
Opened 2024-04-15 17:39 UTC by lzaytseva

Критерии приемки:

- [x]  Система отображает пользователю экран ["Настройки профиля"](https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=2276-1410&mode=design&t=8voUF6B6qaiSQWRM-4)

Доступные действия:

- [x] изменение имени и/или фамилии пользователя
- [x] добавление / изменение изображения (клик по рамке изображения)
- [x] возврат на предыдущий экран (кнопка назад)
- [x] кнопка "Сохранить" всегда активна.

- [x] Требования к тексту: 1-50 символов латинского или русского алфавита (^[a-zA-Zа-яА-Я]{1,50}$)
- [x] После нажатия на кнопку "Сохранить" выполняется Http-запрос:
Запрос от авторизованного пользователя
[{{baseUrl}}profile/name/put](https://212.233.78.3:8080/swagger/docs/index.html#/Profile/put_profile_name_put)
{
"name": "Имя", // может быть пустым
"surname": "" // может быть пустым
}
- [x] после успешного сохранения система выполняет запрос на получение данных профиля пользователя (profile/info/get) и отображает пользователю обновленные данные на странице "Настройка профиля":
В полях формы ввода отображается имя и фамилия (при наличии)

- [x] Обновление фото профиля
[{{baseUrl}}profile/image/put](https://212.233.78.3:8080/swagger/docs/index.html#/Profile/put_profile_image_put)
Ограничений к файлу нет
Предлагается использовать минимальное разрешение 200х200 и все форматы фотографий на телефонах

На данный момент реализовано через PickVisualMediaRequest: можно выбрать любые картинки в общих папках, разрешение у пользователя не запрашивается

P.S. т.к. у сервера проблемы с сертификатом для глайда был создан специальный [модуль](https://github.com/CashAdv/CashADV/blob/feature/76-edit-user-profile/app/src/main/java/app/cashadvisor/profile/presentation/ui/UnsafeOkHttpGlideModule.kt)  с unsafe клиентом т.к. в конструктор его ничего передавать нельзя, просто взяла код из дата модуля, в один файл какой-то выносить не стала, т.к. всё равно этот класс потом можно будет весь удалить.

Вюшки хидеров: [аналитика и трекер](https://github.com/CashAdv/CashADV/blob/feature/76-edit-user-profile/uikit/src/main/java/app/cashadvisor/customView/ProfileHeaderMain.kt) и [настройки](https://github.com/CashAdv/CashADV/blob/feature/76-edit-user-profile/uikit/src/main/java/app/cashadvisor/customView/ProfileHeaderSettings.kt)
На данный момент они просто добавлены на макеты, но загрузку данных на всех экранах не реализовала в рамках этой задачи. Данные сохраняются в [хранилище](https://github.com/CashAdv/CashADV/blob/feature/76-edit-user-profile/app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt) при первой загрузке с сервера, чтобы не делать запросы каждый раз. Нужно будет добавить очищение при логауте.

2024-04-22 13:49 UTC, artwist-polyakov requested changes
Одно замечание. 

По реализации лично мне кажется странным, что мы используем специальные типы ошибок для редактирования профиля. Такие эксепшены кажутся универсальными (вроде нет соединения или анаутентификейтед), но так как нас поджимают сроки мы вряд ли сможем организовать работу сетевого слоя красиво.

2024-04-22 13:49 UTC, artwist-polyakov commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        private const val BLANK_PROFILE_NAME = "Мы тебя не знаем..."
Предлагаю использовать какие-то осмысленные подсказки если имя фамилия пустые
Дизайн нам подсказывает прописать там Имя и Фамилию.
Сейчас плейсходлдер не сбрасывается при редактировании и сложно воспринимается с точки зрения сценария использования

![CleanShot 2024-04-22 at 16 42 39](https://github.com/CashAdv/CashADV/assets/42345388/c5ee46b3-55d0-4756-87a4-cb33cd15ecfa)

2024-04-22 13:58 UTC, artwist-polyakov commented on app/src/main/java/app/cashadvisor/profile/data/mapper/NetworkToProfileExceptionMapper.kt
А мы точно не можем освободиться от повторяющегося кода через инлайн функцию вроде такой? https://github.com/artwist-polyakov/practicum-android-diploma/blob/c6ca229e2af873fd0bfeefab076f031913f7dab2/app/src/main/java/ru/practicum/android/diploma/search/data/HHSearchRepositoryImpl.kt#L73

2024-04-23 19:09 UTC, avanisimov commented on uikit/build.gradle.kts
> +    annotationProcessor(libs.compiler)
libs.compiler - не говорящее название

2024-04-23 19:09 UTC, avanisimov commented on uikit/src/main/java/app/cashadvisor/customView/ProfileHeaderMain.kt
> +    private var ivProfilePic: ImageView
val

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/data/api/ProfileInfoApiService.kt
> +    @Headers("Content-Type: application/json")
должно работать без хедера application/json
оно ж настраивается в NetworkModule

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        private const val BLANK_PROFILE_NAME = "Мы тебя не знаем..."
а откуда вообще эта строчка взялас?

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        }
при такой логике оно может закешироваться навечно и если на сервере что-то поменяется, то мы об этом не узнаем пока не разлогинемся
надо выставить время жизни какоето, или кешировать только в оперативке

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/di/ProfileDataModule.kt
> +        )
лучше создавать шаред префы внутри локалдатасорса лениво, тк сейчас весь этот код будет работать в мейн потоке при инициализации графа зависимостей в конструкторе вьюмодели профиля

не критично, можно не менять

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/di/ProfileDataModule.kt
> +    fun providesMasterKey(): String =
лишняя функция
вроде как написано 
    @Provides
    @Singleton
 но по факту она вызывается прямо на 66 строчке, в обход хилта

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/di/ProfileDataModule.kt
> +        @ProfileSharedPrefs storage: SharedPreferences = providesEncryptedSharedPreferences(context),
= providesEncryptedSharedPreferences(context),
убирай, это бессмысленная заглушка, в DI все параметры методов-фабрик (то шо provides) должны приходить
не должно быть значений по умолчанию

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/presentation/ui/ProfileSettingsFragment.kt
> +        }
надо обработать "else" ветку

2024-04-23 19:09 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/presentation/ui/ProfileSettingsFragment.kt
> +            .setAction("OK") {//dismiss
в ресурсы

2024-04-24 16:17 UTC, lzaytseva commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        private const val BLANK_PROFILE_NAME = "Мы тебя не знаем..."
ой это я на пустой профиль проверку не дописала, фамилию на пустую проверила, а имя с сервера приходит для пустого профиля "мы тебя не знаем", сорри, поправлю

2024-04-24 16:18 UTC, lzaytseva commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        private const val BLANK_PROFILE_NAME = "Мы тебя не знаем..."
@artwist-polyakov а Alexandr это ты уже ввёл фамилию? свою в поле? или оно при первом открытии взялось оттуда?

2024-04-24 16:24 UTC, artwist-polyakov commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        private const val BLANK_PROFILE_NAME = "Мы тебя не знаем..."
> @artwist-polyakov а Alexandr это ты уже ввёл фамилию? свою в поле? или оно при первом открытии взялось оттуда?

Там был плейсхолдер `...`. Alexander уже я ввёл

2024-04-24 17:03 UTC, lzaytseva commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        private const val BLANK_PROFILE_NAME = "Мы тебя не знаем..."
Это не подсказка, это с сервера фамилия приходит "..." для незаполненного профиля, т.к. проверку не дописала, то поэтому и в поле подставилось "...". Поправляю. На их месте я бы, кнч, возвращала null или пустые строки с сервера, а не "мы тебя не знаем" и многоточие

2024-04-24 17:56 UTC, lzaytseva commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        }
@avanisimov мб просто сохранить в репозитории? будет жить, пока живет приложение. Плюс, наверное, зашифрованные префы для имени фамилии не особо нужно

2024-04-24 18:14 UTC, lzaytseva commented on app/src/main/java/app/cashadvisor/profile/data/mapper/NetworkToProfileExceptionMapper.kt
По поводу повторяющихся ошибок есть идея вынести общие ошибки в класс какой-нибудь common exception и его и все классы специальных ошибок от какого-нибудь интерфейса наследовать, в голове до конца сейчас не могу продумать, если и менять это всё, то надо отдельной таской и договориться сначала как

2024-04-24 18:15 UTC, lzaytseva commented on app/src/main/java/app/cashadvisor/profile/di/ProfileDataModule.kt
> +        )
по поводу этого сначала жду ответа, мб вообще не использовать префы и удалить весь этот код

2024-04-24 18:22 UTC, lzaytseva commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        private const val BLANK_PROFILE_NAME = "Мы тебя не знаем..."
тут поправила
![photo_2024-04-24_21-22-08](https://github.com/CashAdv/CashADV/assets/121244389/c04b48a7-f66e-4bbc-a8c0-772ad6b905f9)

2024-04-24 18:51 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        }
Да

2024-05-05 20:22 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/presentation/ui/ProfileSettingsFragment.kt
> +    private fun setImageToIV(uri: String) {
не очень понятное название функции. какую имейдж? в какой ИВ?

2024-05-05 20:22 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/presentation/ui/ProfileSettingsFragment.kt
> +                profilePicUrl = uri.toString()
лучше это проводить через вьюмодель, чтобы был единый флоу данных и консистентность состояния
то есть в этом случае когда приходит результат, то он передаётся вьюмодели, вьюмодель запоминает что выбрали какуюто картинку и апдейтит стейт юая

2024-05-20 08:01 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/profile/data/impl/ProfileInfoRepositoryImpl.kt
> +        }
мьютексы тут оверхед
модельки спецом делаются иммутабельными (data-классами), чтобы не было проблем с конкурентностью
можно сделать без мьютексов
но если используешь мьютексы то лучше делать через метод с лямбдой
```
profileInfoMutex.withLock { 
            
        }
```

2024-05-20 15:33 UTC, avanisimov approved these changes

2024-05-20 15:36 UTC, artwist-polyakov approved these changes

2024-05-20 15:49 UTC, merged