71 password recovery
CashAdv/CashADV pull request #97
Opened 2024-05-07 16:44 UTC by MajoritySky2496

Made a password recovery screen

2024-05-10 05:07 UTC, MajoritySky2496 commented
Есть она проблема которую не могу решить, при вводе не верного когда приходить ошибка "Something went wrong Field 'message' is required for type with serial name 'app.cashadvisor.authorization.data.models.response.ConfirmResetPasswordResponse', but it was missing at path: $" Хотя данное поле существует. При верном вводе кода все работает и никаких ошибок нет. Буду благодарен за помощь)

2024-05-10 19:08 UTC, artwist-polyakov commented
> Есть одна проблема которую не могу решить, при вводе неверного когда приходить ошибка "Something went wrong Field 'message' is required for type with serial name

Привет, проблема о которой ты пишешь происходит потому, что если код не верный, то тебе приходит вот такой ответ

```json
{
  "remaining_attempts": 0,
  "lock_duration": 0,
  "error": "Invalid token for the last code",
  "status_code": 401
}

```
а если верный то вот такой

```json
{
  "message": "Successfully confirmed email",
  "status_code": 200
}

```

ты ожидаешь, что в ответе будет поле message, но его нет.
я рекомендую тебе прежде чем десериализовать json узнать какой у тебя статус код
напрмер ты можешь десериализовать ответ в класс у которого есть только одно поле — статус код.
на основе статус кода уже решать в какой объект совершать десериализацию.

2024-05-11 06:22 UTC, MajoritySky2496 commented
@artwist-polyakov в том то и проблема что я это сделать) ошибка должна обработаться в dataSource как NetworkException, но она ловится раньше в репозитории как обычный exception. Когда дебажил, пару раз обрабатывалось правильно, но в основном какая то чертовщина

2024-05-11 09:37 UTC, artwist-polyakov commented
> @artwist-polyakov в том то и проблема что я это сделать) ошибка должна обработаться в dataSource как NetworkException, но она ловится раньше в репозитории как обычный exception. Когда дебажил, пару раз обрабатывалось правильно, но в основном какая то чертовщина

привет.

Ну как же чертовщина.
Давай еще раз посмотрим на код.
А конкретно вот на этот фрагмент

![CleanShot 2024-05-11 at 11 50 12@2x](https://github.com/CashAdv/CashADV/assets/42345388/913024e2-5732-47e1-8c14-57b5729b4451)

Нас интересует вот этот класс `ResetPasswordConfirmationResponse`

```kotlin

@Serializable
data class ResetPasswordConfirmationResponse(
    val message:String,
    val token:String,
    @SerialName("status_code") val statusCode: Int = 0)

```
именно его ты получаешь в ответ верификацию кода.
там у тебя есть `message` — но его на самом деле нет в ответе.

Я беру, заменяю этот кусок кода вот на такое (параллельно распаковывая опционал в конверторе):

```kotlin

@Serializable
data class ConfirmResetPasswordResponse(
    val message: String? = null,
    @SerialName("status_code") val statusCode: Int = 0
)

```

и тадам — меня пропускает на следующий шаг ввода пароля не смотря на то что статус код неверный. и сам код тоже не верный.
**отсюда я делаю вывод что ты не проверяешь код ответа, который хранится в результате ответа на твой запрос.**

Вообще обрати внимание, что когда ты начинаешь работать с исключениями, то есть смысл также отрабатывать "остальной" кейс — когда ты попадаешь не в предусмотренные программой NetworkExceptions, а в какие-то другие, как в твоем случае.
Тогда можно было бы выводить понятный лог и как то пояснять, что всё же случилось, но у тебя там была пустота, которая никак не логировалась.

2024-05-27 09:20 UTC, artwist-polyakov requested changes
Пара замечаний:

1. Если мы вводим неправильный пароль, то вместе с сообщением о том, что пароль не правильный необходимо также очищать поле ввода. У вьюхи кода есть для этого метод.
2. Может быть сделаем тоаст в котором приведем текущий код подтверждения прям в приложении? чтобы не ходить за ним далеко ?

2024-05-27 15:50 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +fun setEmailConfirmCode(code: String, context: Context) {
передавать контекст в ViewModel запрещенно

2024-05-27 15:50 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +     fun setEmail(
название setEmail наводит на мысль что будет установка e-mail, а по факту выполняется запрос на восстановление пароля
тогда стоит назвать метод requestRecovery или tryToRecovery

при этом у тебя есть состояние инпута емейла в emailInput, можно сюда его дополнительно не передавать

2024-05-27 15:50 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +    }
а что эта подписка делает?

2024-05-27 15:50 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +                    resendCountDownJob!!.cancel()
нельзя вызывать метод через !! - будет краш

2024-05-27 15:50 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +                }
logDebugMessage можно написать один раз

2024-05-27 15:51 UTC, avanisimov commented
Отформатиру, пожалуйста, свой код. сейчас его сложно читать из-за кривой табуляции

2024-05-27 15:59 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/data/impl/ResetPasswordRepositoryImpl.kt
> +            ?: ResetPasswordState(ResetPasswordState.State.Initial)
private val currentState: ResetPasswordState
        get() = _state.value

2024-05-27 15:59 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/domain/ResetDomainMapper.kt
> +    fun toResetPasswordInputDto(email: Email): ResetPasswordInputDto {
домейн слой не должен знать про существование DTO

2024-05-29 17:40 UTC, MajoritySky2496 commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +fun setEmailConfirmCode(code: String, context: Context) {
конекст убрал

2024-05-29 17:41 UTC, MajoritySky2496 commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +     fun setEmail(
исправил

2024-05-29 17:41 UTC, MajoritySky2496 commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +    }
Подсмотрел у ребят, но так и не нашел ей применение, убрал ее

2024-05-29 17:42 UTC, MajoritySky2496 commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +                    resendCountDownJob!!.cancel()
исправил

2024-05-29 17:42 UTC, MajoritySky2496 commented on app/src/main/java/app/cashadvisor/authorization/presentation/viewmodel/PasswordRecoveryViewModel.kt
> +                }
исправил

2024-05-29 17:42 UTC, MajoritySky2496 commented on app/src/main/java/app/cashadvisor/authorization/domain/ResetDomainMapper.kt
> +    fun toResetPasswordInputDto(email: Email): ResetPasswordInputDto {
исправил

2024-06-04 19:43 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/presentation/ui/PasswordRecoveryFragment.kt
> +                        viewModel.navigateBackToEmailState()
1 - сейчас у тебя логика "как обрабатывать кнопку назад?" находится по факту во фрагменте
2 - requireActivity().onBackPressedDispatcher.addCallback вызывается много раз и в итоге много колбеков накапливается в диспатчере

лучше один раз в начале жизни фрагмента прокинуть onBackPressed внутрь вьюмодели, а вот он уже сделает логику when (state) {....} и сайд-эффектами будет управлять фрагментом

2024-06-04 19:43 UTC, avanisimov commented on app/src/main/java/app/cashadvisor/authorization/presentation/ui/PasswordRecoveryFragment.kt
> +            .setActionTextColor(resources.getColor(R.color.white, null))
а чего тему не передаёшь?

2024-06-05 14:29 UTC, artwist-polyakov approved these changes
У меня замечаний нет (ну кроме идеи про код в тоасте, которая не может быть основанием не апрувить ревью)

2024-06-05 18:37 UTC, MajoritySky2496 commented on app/src/main/java/app/cashadvisor/authorization/presentation/ui/PasswordRecoveryFragment.kt
> +            .setActionTextColor(resources.getColor(R.color.white, null))
не понимал зачем это нужно, теперь разобрался

2024-06-10 06:08 UTC, avanisimov approved these changes

2024-06-10 15:51 UTC, merged